const ONBOARDING_DATA = {
    "registro":  [
                     {
                         "No.":  1,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1193156026,
                         "NOMBRE COMPLETO":  "Sara Isabel Molina Sánchez",
                         "CORREO ELECTRÓNICO":  "Molinasara453@gmail.com",
                         "TELÉFONO MÓVIL":  3245742876,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  4,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  72,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  2,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1022988349,
                         "NOMBRE COMPLETO":  "Michelle Geraldine Bejarano Torres",
                         "CORREO ELECTRÓNICO":  "michelletorres2593@hotmail.com",
                         "TELÉFONO MÓVIL":  3123702518,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  2,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  4,
                         "SIMULACIÓN CON IA 20%":  4,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  62,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  3,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1016001652,
                         "NOMBRE COMPLETO":  "Helen Sofia Calderon Camelo",
                         "CORREO ELECTRÓNICO":  "helencalderon910@gmail.com",
                         "TELÉFONO MÓVIL":  "‪3239227093‬",
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  4,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  70,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  4,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1012385263,
                         "NOMBRE COMPLETO":  "Cindy Paola Cuellar Montoya",
                         "CORREO ELECTRÓNICO":  "Cindypaolacuellar@gmail.com",
                         "TELÉFONO MÓVIL":  3172616867,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  3,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  3,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  65,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  "Llega tarde "
                     },
                     {
                         "No.":  5,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1001314657,
                         "NOMBRE COMPLETO":  "Thomas Bernardo Fernandez Laverde",
                         "CORREO ELECTRÓNICO":  "tfernandezlaverde@gmail.com",
                         "TELÉFONO MÓVIL":  3103798566,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  4,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  72,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  6,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  52956322,
                         "NOMBRE COMPLETO":  "Julie Caterine Villalobos Ortiz",
                         "CORREO ELECTRÓNICO":  "Juliecaterine23@gmail.com",
                         "TELÉFONO MÓVIL":  3213264788,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  5,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  4,
                         "SIMULACIÓN CON IA 20%":  4,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  69,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  7,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  10191156098,
                         "NOMBRE COMPLETO":  "Yaricet Bricet Cárcamo Morales",
                         "CORREO ELECTRÓNICO":  "Yaricetbricet@gmail.com",
                         "TELÉFONO MÓVIL":  3008533917,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  4,
                         "SIMULACIÓN CON IA 20%":  3,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  62,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  8,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1033096735,
                         "NOMBRE COMPLETO":  "Pablo Steven Ochoa Rodriguez",
                         "CORREO ELECTRÓNICO":  "Pablorodriguez8q@gmail.com",
                         "TELÉFONO MÓVIL":  3196588439,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  3,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  5,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  4,
                         "NOTA FINAL":  81,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  9,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1000219286,
                         "NOMBRE COMPLETO":  "Lucia Fernanda Cruz Canchila",
                         "CORREO ELECTRÓNICO":  "Luciacruz0414@gmail.com",
                         "TELÉFONO MÓVIL":  3005145730,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  2,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  5,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  68,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  "Llega tarde "
                     },
                     {
                         "No.":  10,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1004961429,
                         "NOMBRE COMPLETO":  "Jhon Stiven Marin Valencia",
                         "CORREO ELECTRÓNICO":  "jhonstivenmarin02@gmail.com",
                         "TELÉFONO MÓVIL":  3219466413,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  3,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  3,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  4,
                         "SIMULACIÓN CON IA 20%":  4,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  4,
                         "NOTA FINAL":  73,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  "Llega tarde "
                     },
                     {
                         "No.":  11,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  53121281,
                         "NOMBRE COMPLETO":  "Yulieth Paola Rodriguez Cañon",
                         "CORREO ELECTRÓNICO":  "ypaolarodriguez14@gmail.com",
                         "TELÉFONO MÓVIL":  3112142736,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  4,
                         "NOTA FINAL":  78,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  12,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1019138287,
                         "NOMBRE COMPLETO":  "Natalia Fernanda Mendieta Oicata",
                         "CORREO ELECTRÓNICO":  "nataliamendieta2025@gmail.com",
                         "TELÉFONO MÓVIL":  3003020830,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  5,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  4,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  67,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  13,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1019145849,
                         "NOMBRE COMPLETO":  "Jhonatan David Londoño Baldovino",
                         "CORREO ELECTRÓNICO":  "Jdlbaldovino199@gmail.com",
                         "TELÉFONO MÓVIL":  3208836403,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  3,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  2,
                         "NOTA FINAL":  62,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  14,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1001056884,
                         "NOMBRE COMPLETO":  "David Felipe Hernández Hernández",
                         "CORREO ELECTRÓNICO":  "david.hernandez.dtk@gmail.com",
                         "TELÉFONO MÓVIL":  3028250517,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  3,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  63,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  15,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1024585365,
                         "NOMBRE COMPLETO":  "Cristian David Celis Garcia",
                         "CORREO ELECTRÓNICO":  "cristianceliss9719@gmail.com",
                         "TELÉFONO MÓVIL":  3216686201,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  4,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  73,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  "Llega tarde "
                     },
                     {
                         "No.":  16,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1000547797,
                         "NOMBRE COMPLETO":  "Kamy Lizeth Rios Gomez",
                         "CORREO ELECTRÓNICO":  "riosgomezkamy@gmail.com",
                         "TELÉFONO MÓVIL":  3112534635,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  5,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  2,
                         "EVALUACIÓN TÉCNICA 10%":  5,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  90,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  17,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1023867138,
                         "NOMBRE COMPLETO":  "Yisell Dayana Castro González",
                         "CORREO ELECTRÓNICO":  "Gonzalezdayanna730@gmail.com",
                         "TELÉFONO MÓVIL":  3143600585,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  4,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  2,
                         "NOTA FINAL":  72,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  18,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1000810776,
                         "NOMBRE COMPLETO":  "Nataly Andrea Maecha Lizarazo",
                         "CORREO ELECTRÓNICO":  "natamahecha23@gmail.com",
                         "TELÉFONO MÓVIL":  3204984051,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  2,
                         "EVALUACIÓN TÉCNICA 10%":  4,
                         "SIMULACIÓN CON IA 20%":  4,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  2,
                         "NOTA FINAL":  74,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  19,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1001271946,
                         "NOMBRE COMPLETO":  "Luisa Fernanda Rodríguez Sarmiento",
                         "CORREO ELECTRÓNICO":  "feryantonella13@gmail.com",
                         "TELÉFONO MÓVIL":  3054399778,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  3,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  4,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  74,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  "Presentación personal"
                     },
                     {
                         "No.":  20,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1117813165,
                         "NOMBRE COMPLETO":  "Yedinson Stiven Ramirez Perdómo",
                         "CORREO ELECTRÓNICO":  "kramirezperdomo@gmail.com",
                         "TELÉFONO MÓVIL":  3506517824,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  5,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                         "EVALUACIÓN TÉCNICA 10%":  5,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  94,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  21,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1045686807,
                         "NOMBRE COMPLETO":  "Gisell Del Carmen Cabrera Maldonado",
                         "CORREO ELECTRÓNICO":  "cgisell890@gmail.com",
                         "TELÉFONO MÓVIL":  3017718956,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  3,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  5,
                         "EVALUACIÓN TÉCNICA 10%":  4,
                         "SIMULACIÓN CON IA 20%":  2,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  2,
                         "NOTA FINAL":  58,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  "Actitud"
                     },
                     {
                         "No.":  22,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1070595836,
                         "NOMBRE COMPLETO":  "Hebert Julián Casilimas Ricardo",
                         "CORREO ELECTRÓNICO":  "julian180703@icloud.com",
                         "TELÉFONO MÓVIL":  3229087879,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                         "EVALUACIÓN TÉCNICA 10%":  5,
                         "SIMULACIÓN CON IA 20%":  5,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  91,
                         "APRUEBA":  "Aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  23,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1140850536,
                         "NOMBRE COMPLETO":  "Nelvis Mirleth Gutiérrez Orozco",
                         "CORREO ELECTRÓNICO":  "Milrthgutierrez@gmail.com",
                         "TELÉFONO MÓVIL":  3028092333,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  3,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  3,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  2,
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  3,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  1,
                         "NOTA FINAL":  56,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  "Actitud "
                     },
                     {
                         "No.":  24,
                         "CAMPAÑA":  "Posgrados",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1073709574,
                         "NOMBRE COMPLETO":  "Johan Sebastian Peña Ramos",
                         "CORREO ELECTRÓNICO":  "seebastian0118@gmail.com",
                         "TELÉFONO MÓVIL":  3138749486,
                         "FORMADOR":  "Todas",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                         "EVALUACIÓN TÉCNICA 10%":  3,
                         "SIMULACIÓN CON IA 20%":  2,
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                         "NOTA FINAL":  53,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  25,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1001187759,
                         "NOMBRE COMPLETO":  "Julian David Jiménez Moreno",
                         "CORREO ELECTRÓNICO":  "Julian.david.jimenez.moreno@gmail.com ",
                         "TELÉFONO MÓVIL":  3124832044,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  4,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  26,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1012455544,
                         "NOMBRE COMPLETO":  "Claudia Yadira Suta Torres ",
                         "CORREO ELECTRÓNICO":  "claudiasuta029@gmail.com",
                         "TELÉFONO MÓVIL":  3227861878,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  4,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  27,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1001056755,
                         "NOMBRE COMPLETO":  "Cristian Manuel Jiménez Gómez ",
                         "CORREO ELECTRÓNICO":  "jimenezsc07@gmail.com",
                         "TELÉFONO MÓVIL":  3123926446,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  3,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  3,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  28,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1000328420,
                         "NOMBRE COMPLETO":  "Miguel Ángel Becerra Garcia",
                         "CORREO ELECTRÓNICO":  "Saclaro920@gmail.com",
                         "TELÉFONO MÓVIL":  3223167270,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  3,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  3,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  29,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1006118253,
                         "NOMBRE COMPLETO":  "Alex Esteban Angarita Lozano",
                         "CORREO ELECTRÓNICO":  "angarita20162001@gmail.com",
                         "TELÉFONO MÓVIL":  3012268430,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  3,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  3,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  30,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1073671475,
                         "NOMBRE COMPLETO":  "Dana Yurleidy Lugo Castro ",
                         "CORREO ELECTRÓNICO":  "danalugo12345@gmail.com",
                         "TELÉFONO MÓVIL":  3147647259,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  4,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  31,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1013670551,
                         "NOMBRE COMPLETO":  "Andersson Stiven Lozano Martinez ",
                         "CORREO ELECTRÓNICO":  "andersson19892014@gmail.com",
                         "TELÉFONO MÓVIL":  3244759449,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "(empty)",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  -2146826273,
                         "APRUEBA":  -2146826273,
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  32,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1007343398,
                         "NOMBRE COMPLETO":  "Duvan Alejandro Díaz Landinez",
                         "CORREO ELECTRÓNICO":  "Alejithodiax@gmail.com",
                         "TELÉFONO MÓVIL":  3026595949,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  4,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  33,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1007845676,
                         "NOMBRE COMPLETO":  "Brandon Stiven Garces Arcos",
                         "CORREO ELECTRÓNICO":  "Brandongarces2@gmail.com ",
                         "TELÉFONO MÓVIL":  3223299162,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  4,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     },
                     {
                         "No.":  34,
                         "CAMPAÑA":  "Pregrado Virtual",
                         "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                         "CARGO":  "Auxiliar gestor  de vinculaciones",
                         "No. DOCUMENTO":  1033772502,
                         "NOMBRE COMPLETO":  "Juan Sebastian Acevedo Salazar ",
                         "CORREO ELECTRÓNICO":  "juansevedo02@gmail.com",
                         "TELÉFONO MÓVIL":  3025718737,
                         "FORMADOR":  "Karen Margarita Puerta",
                         "PRESENTACIÓN PERSONAL 5%":  4,
                         "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                         "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                         "EVALUACIÓN TÉCNICA 10%":  "",
                         "SIMULACIÓN CON IA 20%":  "",
                         "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                         "NOTA FINAL":  4,
                         "APRUEBA":  "No aprueba",
                         "OBSERVACIONES":  ""
                     }
                 ],
    "ojt":  [
                {
                    "No. DOCUMENTO":  1193156026,
                    "NOMBRE COMPLETO":  "Sara Isabel Molina Sánchez",
                    "CORREO ELECTRÓNICO":  "Molinasara453@gmail.com",
                    "TELÉFONO MÓVIL":  3245742876,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  72,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1016001652,
                    "NOMBRE COMPLETO":  "Helen Sofia Calderon Camelo",
                    "CORREO ELECTRÓNICO":  "helencalderon910@gmail.com",
                    "TELÉFONO MÓVIL":  "‪3239227093‬",
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  70,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1001314657,
                    "NOMBRE COMPLETO":  "Thomas Bernardo Fernandez Laverde",
                    "CORREO ELECTRÓNICO":  "tfernandezlaverde@gmail.com",
                    "TELÉFONO MÓVIL":  3103798566,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  72,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1033096735,
                    "NOMBRE COMPLETO":  "Pablo Steven Ochoa Rodriguez",
                    "CORREO ELECTRÓNICO":  "Pablorodriguez8q@gmail.com",
                    "TELÉFONO MÓVIL":  3196588439,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  81,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1004961429,
                    "NOMBRE COMPLETO":  "Jhon Stiven Marin Valencia",
                    "CORREO ELECTRÓNICO":  "jhonstivenmarin02@gmail.com",
                    "TELÉFONO MÓVIL":  3219466413,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  73,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  53121281,
                    "NOMBRE COMPLETO":  "Yulieth Paola Rodriguez Cañon",
                    "CORREO ELECTRÓNICO":  "ypaolarodriguez14@gmail.com",
                    "TELÉFONO MÓVIL":  3112142736,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  78,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1024585365,
                    "NOMBRE COMPLETO":  "Cristian David Celis Garcia",
                    "CORREO ELECTRÓNICO":  "cristianceliss9719@gmail.com",
                    "TELÉFONO MÓVIL":  3216686201,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  73,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1000547797,
                    "NOMBRE COMPLETO":  "Kamy Lizeth Rios Gomez",
                    "CORREO ELECTRÓNICO":  "riosgomezkamy@gmail.com",
                    "TELÉFONO MÓVIL":  3112534635,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  90,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1023867138,
                    "NOMBRE COMPLETO":  "Yisell Dayana Castro González",
                    "CORREO ELECTRÓNICO":  "Gonzalezdayanna730@gmail.com",
                    "TELÉFONO MÓVIL":  3143600585,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  72,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1000810776,
                    "NOMBRE COMPLETO":  "Nataly Andrea Maecha Lizarazo",
                    "CORREO ELECTRÓNICO":  "natamahecha23@gmail.com",
                    "TELÉFONO MÓVIL":  3204984051,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  74,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1001271946,
                    "NOMBRE COMPLETO":  "Luisa Fernanda Rodríguez Sarmiento",
                    "CORREO ELECTRÓNICO":  "feryantonella13@gmail.com",
                    "TELÉFONO MÓVIL":  3054399778,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  74,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1117813165,
                    "NOMBRE COMPLETO":  "Yedinson Stiven Ramirez Perdómo",
                    "CORREO ELECTRÓNICO":  "kramirezperdomo@gmail.com",
                    "TELÉFONO MÓVIL":  3506517824,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  94,
                    "APRUEBA":  "Aprueba"
                },
                {
                    "No. DOCUMENTO":  1070595836,
                    "NOMBRE COMPLETO":  "Hebert Julián Casilimas Ricardo",
                    "CORREO ELECTRÓNICO":  "julian180703@icloud.com",
                    "TELÉFONO MÓVIL":  3229087879,
                    "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                    "CAMPAÑA":  "Posgrados",
                    "NOTA FINAL":  91,
                    "APRUEBA":  "Aprueba"
                }
            ],
    "ojt_diario":  [
                       {
                           "N°":  1,
                           "No. DOCUMENTO":  1193156026,
                           "NOMBRE COMPLETO":  "Sara Isabel Molina Sánchez",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-01",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  2,
                           "No. DOCUMENTO":  1016001652,
                           "NOMBRE COMPLETO":  "Helen Sofia Calderon Camelo",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-01",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  3,
                           "No. DOCUMENTO":  1001314657,
                           "NOMBRE COMPLETO":  "Thomas Bernardo Fernandez Laverde",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-01",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  4,
                           "No. DOCUMENTO":  1033096735,
                           "NOMBRE COMPLETO":  "Pablo Steven Ochoa Rodriguez",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-01",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  5,
                           "No. DOCUMENTO":  1004961429,
                           "NOMBRE COMPLETO":  "Jhon Stiven Marin Valencia",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-01",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  6,
                           "No. DOCUMENTO":  53121281,
                           "NOMBRE COMPLETO":  "Yulieth Paola Rodriguez Cañon",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-01",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  7,
                           "No. DOCUMENTO":  1024585365,
                           "NOMBRE COMPLETO":  "Cristian David Celis Garcia",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-08",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  8,
                           "No. DOCUMENTO":  1000547797,
                           "NOMBRE COMPLETO":  "Kamy Lizeth Rios Gomez",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-08",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  9,
                           "No. DOCUMENTO":  1023867138,
                           "NOMBRE COMPLETO":  "Yisell Dayana Castro González",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-08",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  10,
                           "No. DOCUMENTO":  1000810776,
                           "NOMBRE COMPLETO":  "Nataly Andrea Maecha Lizarazo",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-08",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  11,
                           "No. DOCUMENTO":  1001271946,
                           "NOMBRE COMPLETO":  "Luisa Fernanda Rodríguez Sarmiento",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-08",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  12,
                           "No. DOCUMENTO":  1117813165,
                           "NOMBRE COMPLETO":  "Yedinson Stiven Ramirez Perdómo",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-08",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       },
                       {
                           "N°":  13,
                           "No. DOCUMENTO":  1070595836,
                           "NOMBRE COMPLETO":  "Hebert Julián Casilimas Ricardo",
                           "CAMPAÑA":  "Posgrados",
                           "FORMADOR":  "Todas",
                           "DÍA":  "",
                           "FECHA":  "2026-07-08",
                           "MATRÍCULAS":  "",
                           "ADERECIA":  "",
                           "ACTITUD (1-5)":  "",
                           "OBSERVACIONES":  ""
                       }
                   ],
    "ojt_aprobados":  [
                          {
                              "No.":  1,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1193156026,
                              "NOMBRE COMPLETO":  "Sara Isabel Molina Sánchez",
                              "CORREO ELECTRÓNICO":  "Molinasara453@gmail.com",
                              "TELÉFONO MÓVIL":  3245742876,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  4,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  72,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  2,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1022988349,
                              "NOMBRE COMPLETO":  "Michelle Geraldine Bejarano Torres",
                              "CORREO ELECTRÓNICO":  "michelletorres2593@hotmail.com",
                              "TELÉFONO MÓVIL":  3123702518,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  2,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  4,
                              "SIMULACIÓN CON IA 20%":  4,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  62,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  3,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1016001652,
                              "NOMBRE COMPLETO":  "Helen Sofia Calderon Camelo",
                              "CORREO ELECTRÓNICO":  "helencalderon910@gmail.com",
                              "TELÉFONO MÓVIL":  "‪3239227093‬",
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  4,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  70,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  4,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1012385263,
                              "NOMBRE COMPLETO":  "Cindy Paola Cuellar Montoya",
                              "CORREO ELECTRÓNICO":  "Cindypaolacuellar@gmail.com",
                              "TELÉFONO MÓVIL":  3172616867,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  3,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  3,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  65,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  "Llega tarde "
                          },
                          {
                              "No.":  5,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1001314657,
                              "NOMBRE COMPLETO":  "Thomas Bernardo Fernandez Laverde",
                              "CORREO ELECTRÓNICO":  "tfernandezlaverde@gmail.com",
                              "TELÉFONO MÓVIL":  3103798566,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  4,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  72,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  6,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  52956322,
                              "NOMBRE COMPLETO":  "Julie Caterine Villalobos Ortiz",
                              "CORREO ELECTRÓNICO":  "Juliecaterine23@gmail.com",
                              "TELÉFONO MÓVIL":  3213264788,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  5,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  4,
                              "SIMULACIÓN CON IA 20%":  4,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  69,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  7,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  10191156098,
                              "NOMBRE COMPLETO":  "Yaricet Bricet Cárcamo Morales",
                              "CORREO ELECTRÓNICO":  "Yaricetbricet@gmail.com",
                              "TELÉFONO MÓVIL":  3008533917,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  4,
                              "SIMULACIÓN CON IA 20%":  3,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  62,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  8,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1033096735,
                              "NOMBRE COMPLETO":  "Pablo Steven Ochoa Rodriguez",
                              "CORREO ELECTRÓNICO":  "Pablorodriguez8q@gmail.com",
                              "TELÉFONO MÓVIL":  3196588439,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  3,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  5,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  4,
                              "NOTA FINAL":  81,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  9,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1000219286,
                              "NOMBRE COMPLETO":  "Lucia Fernanda Cruz Canchila",
                              "CORREO ELECTRÓNICO":  "Luciacruz0414@gmail.com",
                              "TELÉFONO MÓVIL":  3005145730,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  2,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  5,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  68,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  "Llega tarde "
                          },
                          {
                              "No.":  10,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1004961429,
                              "NOMBRE COMPLETO":  "Jhon Stiven Marin Valencia",
                              "CORREO ELECTRÓNICO":  "jhonstivenmarin02@gmail.com",
                              "TELÉFONO MÓVIL":  3219466413,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  3,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  3,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  4,
                              "SIMULACIÓN CON IA 20%":  4,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  4,
                              "NOTA FINAL":  73,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  "Llega tarde "
                          },
                          {
                              "No.":  11,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  53121281,
                              "NOMBRE COMPLETO":  "Yulieth Paola Rodriguez Cañon",
                              "CORREO ELECTRÓNICO":  "ypaolarodriguez14@gmail.com",
                              "TELÉFONO MÓVIL":  3112142736,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  4,
                              "NOTA FINAL":  78,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  12,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-01",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1019138287,
                              "NOMBRE COMPLETO":  "Natalia Fernanda Mendieta Oicata",
                              "CORREO ELECTRÓNICO":  "nataliamendieta2025@gmail.com",
                              "TELÉFONO MÓVIL":  3003020830,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  5,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  4,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  67,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  13,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1019145849,
                              "NOMBRE COMPLETO":  "Jhonatan David Londoño Baldovino",
                              "CORREO ELECTRÓNICO":  "Jdlbaldovino199@gmail.com",
                              "TELÉFONO MÓVIL":  3208836403,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  3,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  2,
                              "NOTA FINAL":  62,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  14,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1001056884,
                              "NOMBRE COMPLETO":  "David Felipe Hernández Hernández",
                              "CORREO ELECTRÓNICO":  "david.hernandez.dtk@gmail.com",
                              "TELÉFONO MÓVIL":  3028250517,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  3,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  63,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  15,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1024585365,
                              "NOMBRE COMPLETO":  "Cristian David Celis Garcia",
                              "CORREO ELECTRÓNICO":  "cristianceliss9719@gmail.com",
                              "TELÉFONO MÓVIL":  3216686201,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  4,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  73,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  "Llega tarde "
                          },
                          {
                              "No.":  16,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1000547797,
                              "NOMBRE COMPLETO":  "Kamy Lizeth Rios Gomez",
                              "CORREO ELECTRÓNICO":  "riosgomezkamy@gmail.com",
                              "TELÉFONO MÓVIL":  3112534635,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  5,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  2,
                              "EVALUACIÓN TÉCNICA 10%":  5,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  90,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  17,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1023867138,
                              "NOMBRE COMPLETO":  "Yisell Dayana Castro González",
                              "CORREO ELECTRÓNICO":  "Gonzalezdayanna730@gmail.com",
                              "TELÉFONO MÓVIL":  3143600585,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  4,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  2,
                              "NOTA FINAL":  72,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  18,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1000810776,
                              "NOMBRE COMPLETO":  "Nataly Andrea Maecha Lizarazo",
                              "CORREO ELECTRÓNICO":  "natamahecha23@gmail.com",
                              "TELÉFONO MÓVIL":  3204984051,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  2,
                              "EVALUACIÓN TÉCNICA 10%":  4,
                              "SIMULACIÓN CON IA 20%":  4,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  2,
                              "NOTA FINAL":  74,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  19,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1001271946,
                              "NOMBRE COMPLETO":  "Luisa Fernanda Rodríguez Sarmiento",
                              "CORREO ELECTRÓNICO":  "feryantonella13@gmail.com",
                              "TELÉFONO MÓVIL":  3054399778,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  3,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  4,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  74,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  "Presentación personal"
                          },
                          {
                              "No.":  20,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1117813165,
                              "NOMBRE COMPLETO":  "Yedinson Stiven Ramirez Perdómo",
                              "CORREO ELECTRÓNICO":  "kramirezperdomo@gmail.com",
                              "TELÉFONO MÓVIL":  3506517824,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  5,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  5,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                              "EVALUACIÓN TÉCNICA 10%":  5,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  94,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  21,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1045686807,
                              "NOMBRE COMPLETO":  "Gisell Del Carmen Cabrera Maldonado",
                              "CORREO ELECTRÓNICO":  "cgisell890@gmail.com",
                              "TELÉFONO MÓVIL":  3017718956,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  3,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  5,
                              "EVALUACIÓN TÉCNICA 10%":  4,
                              "SIMULACIÓN CON IA 20%":  2,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  2,
                              "NOTA FINAL":  58,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  "Actitud"
                          },
                          {
                              "No.":  22,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1070595836,
                              "NOMBRE COMPLETO":  "Hebert Julián Casilimas Ricardo",
                              "CORREO ELECTRÓNICO":  "julian180703@icloud.com",
                              "TELÉFONO MÓVIL":  3229087879,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                              "EVALUACIÓN TÉCNICA 10%":  5,
                              "SIMULACIÓN CON IA 20%":  5,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  91,
                              "APRUEBA":  "Aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  23,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1140850536,
                              "NOMBRE COMPLETO":  "Nelvis Mirleth Gutiérrez Orozco",
                              "CORREO ELECTRÓNICO":  "Milrthgutierrez@gmail.com",
                              "TELÉFONO MÓVIL":  3028092333,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  3,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  3,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  2,
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  3,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  1,
                              "NOTA FINAL":  56,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  "Actitud "
                          },
                          {
                              "No.":  24,
                              "CAMPAÑA":  "Posgrados",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-08",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1073709574,
                              "NOMBRE COMPLETO":  "Johan Sebastian Peña Ramos",
                              "CORREO ELECTRÓNICO":  "seebastian0118@gmail.com",
                              "TELÉFONO MÓVIL":  3138749486,
                              "FORMADOR":  "Todas",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  4,
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  3,
                              "EVALUACIÓN TÉCNICA 10%":  3,
                              "SIMULACIÓN CON IA 20%":  2,
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  3,
                              "NOTA FINAL":  53,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  25,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1001187759,
                              "NOMBRE COMPLETO":  "Julian David Jiménez Moreno",
                              "CORREO ELECTRÓNICO":  "Julian.david.jimenez.moreno@gmail.com ",
                              "TELÉFONO MÓVIL":  3124832044,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  4,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  26,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1012455544,
                              "NOMBRE COMPLETO":  "Claudia Yadira Suta Torres ",
                              "CORREO ELECTRÓNICO":  "claudiasuta029@gmail.com",
                              "TELÉFONO MÓVIL":  3227861878,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  4,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  27,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1001056755,
                              "NOMBRE COMPLETO":  "Cristian Manuel Jiménez Gómez ",
                              "CORREO ELECTRÓNICO":  "jimenezsc07@gmail.com",
                              "TELÉFONO MÓVIL":  3123926446,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  3,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  3,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  28,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1000328420,
                              "NOMBRE COMPLETO":  "Miguel Ángel Becerra Garcia",
                              "CORREO ELECTRÓNICO":  "Saclaro920@gmail.com",
                              "TELÉFONO MÓVIL":  3223167270,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  3,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  3,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  29,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1006118253,
                              "NOMBRE COMPLETO":  "Alex Esteban Angarita Lozano",
                              "CORREO ELECTRÓNICO":  "angarita20162001@gmail.com",
                              "TELÉFONO MÓVIL":  3012268430,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  3,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  3,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  30,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1073671475,
                              "NOMBRE COMPLETO":  "Dana Yurleidy Lugo Castro ",
                              "CORREO ELECTRÓNICO":  "danalugo12345@gmail.com",
                              "TELÉFONO MÓVIL":  3147647259,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  4,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  31,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1013670551,
                              "NOMBRE COMPLETO":  "Andersson Stiven Lozano Martinez ",
                              "CORREO ELECTRÓNICO":  "andersson19892014@gmail.com",
                              "TELÉFONO MÓVIL":  3244759449,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "(empty)",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  -2146826273,
                              "APRUEBA":  -2146826273,
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  32,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1007343398,
                              "NOMBRE COMPLETO":  "Duvan Alejandro Díaz Landinez",
                              "CORREO ELECTRÓNICO":  "Alejithodiax@gmail.com",
                              "TELÉFONO MÓVIL":  3026595949,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  4,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  33,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1007845676,
                              "NOMBRE COMPLETO":  "Brandon Stiven Garces Arcos",
                              "CORREO ELECTRÓNICO":  "Brandongarces2@gmail.com ",
                              "TELÉFONO MÓVIL":  3223299162,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  4,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          },
                          {
                              "No.":  34,
                              "CAMPAÑA":  "Pregrado Virtual",
                              "FECHA DE INGRESO A FORMACIÓN":  "2026-07-21",
                              "CARGO":  "Auxiliar gestor  de vinculaciones",
                              "No. DOCUMENTO":  1033772502,
                              "NOMBRE COMPLETO":  "Juan Sebastian Acevedo Salazar ",
                              "CORREO ELECTRÓNICO":  "juansevedo02@gmail.com",
                              "TELÉFONO MÓVIL":  3025718737,
                              "FORMADOR":  "Karen Margarita Puerta",
                              "PRESENTACIÓN PERSONAL 5%":  4,
                              "PARTICIPACIÓN Y PUNTUALIDAD 10%":  "",
                              "EVALUACIÓN CONOCIMIENTO (DIA 2) 5%":  "",
                              "EVALUACIÓN TÉCNICA 10%":  "",
                              "SIMULACIÓN CON IA 20%":  "",
                              "EVALUACIÓN FINAL (CLÍNICA DE VENTAS) 50%":  "",
                              "NOTA FINAL":  4,
                              "APRUEBA":  "No aprueba",
                              "OBSERVACIONES":  ""
                          }
                      ],
    "actualizado":  "2026-07-24 14:15:45"
};
